// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPICore5_0W.Models;

namespace WebAPICore5_0W.Migrations
{
    [DbContext(typeof(OrdersTripsAppDBContext))]
    partial class OrdersTripsAppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Cyrillic_General_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPICore5_0W.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Fio")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("fio");

                    b.Property<int?>("IdTrip")
                        .HasColumnType("int")
                        .HasColumnName("idTrip");

                    b.HasKey("Id");

                    b.HasIndex("IdTrip");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WebAPICore5_0W.Models.Trip", b =>
                {
                    b.Property<int>("IdTrip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idTrip")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FinishLocation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("finishLocation");

                    b.Property<bool?>("Ordered")
                        .HasColumnType("bit")
                        .HasColumnName("ordered");

                    b.Property<int?>("Price")
                        .HasColumnType("int")
                        .HasColumnName("price");

                    b.Property<string>("StartLocation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("startLocation");

                    b.HasKey("IdTrip");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("WebAPICore5_0W.Models.Order", b =>
                {
                    b.HasOne("WebAPICore5_0W.Models.Trip", "IdTripNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("IdTrip")
                        .HasConstraintName("FK_Orders_Trips")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("IdTripNavigation");
                });

            modelBuilder.Entity("WebAPICore5_0W.Models.Trip", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
